### ISSUE TITLE
SRA support

### ISSUE THREAD

**Issue by kopardev** [skchronicles/RNA-seek#20] opened 2021-03-25 18:28 UTC
- `--input` can accept comma-separated SRR numbers OR
- `sradownload` subcommand to download files before running pipeline

**Comment by skchronicles** [comment] 2021-03-25 19:44
This issue is a duplicate of issue #9.
I am going to close this issue and copy your notes into issue #9 so everything is organized in the same place.

**Closed by skchronicles** 2021-03-25 19:44 UTC
